---
title: "PeakSegDP::cDPA(), a quadratic time constrained dynamic programming algorithm"
author: "Anirban Chetia"
date: "2020-08-03"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PeakSegDP::cDPA(), a quadratic time constrained dynamic programming algorithm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Abstract
Peak detection is a central problem in genomic data analysis, with algorithms for this task being unsupervised and mostly effective for a single data type and pattern only. In response to this, "PeakSeg" was proposed, which is a constrained maximum Poisson likelihood segmentation model (more information on which can be found [here](https://dl.acm.org/doi/abs/10.5555/3045118.3045154)).

The package `PeakSegDP` provides the baseline that computes an approximate solution (subject to a constraint on the number of segments) to the up-down (changes must alternate following an up-down trend) constrained problem which satisfies the PeakSeg constraints via the constrained dynamic programming algorithm (cDPA).

## Time Complexity
cDPA is known to be a quadratic time algorithm, and the implementation for the same in `PeakSegDP::cDPA` is a low-level interface to the C solver, which retains the same computational complexity.

## Reference
Source enacting as reference for the above information includes the [github repository](https://github.com/tdhock/PeakSegDP) and this [pdf](http://proceedings.mlr.press/v37/hocking15.pdf).

## Testing
We can verify the quadratic time complexity for this algorithm by a run with our time complexity analysis functions `asymptoticTimings` and `asymptoticTimeComplexityClass`:
```r
library(testComplexity)
df <- asymptoticTimings(PeakSegDP::cDPA(rpois(data.sizes, 1), rep(1, length(rpois(dta.sizes, 1))), 3L), data.sizes = 10^seq(1, 4, by = 0.5))
asymptoticTimeComplexityClass(df)
#> [1] "quadratic"
```

<sup>Created on 2020-08-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
